parameters:
    ahs_image:
        image_path: "%application_path%/../images/ahs_images/"
        image_dir: "/images/ahs_images/"
        image_prefix: "image-"
        thumbnail_path: "%application_path%/../images/ahs_images/thumbnails/"
        thumbnail_dir: "/images/ahs_images/thumbnails/"
        thumbnail_prefix: "thumb-"
        thumbnail_max_size: "64"
        cache_url: "images/ahs_images/cache"
        cache_path: "%application_path%/../images/ahs_images/cache/"

    purifier:
        linkify: true
        allowedhtml: "a[href], p"